apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    bucket: shared
spec:
  capacity:
    storage: 100Mi
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/k8s-pv-share
    server: 192.168.0.85
  #mountOptions:
  #  - hard
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
spec:
  selector:
    matchLabels:
      bucket: shared
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
