apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.pvName }}
  namespace: {{ .Release.Namespace }}
  labels:
    bucket: shared
spec:
  capacity:
    storage: {{ .Values.volume.capacity }}
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.volume.nfsPath }}
    server: {{ .Values.volume.nfsHost }}
  #mountOptions:
  #  - hard
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.volume.pvName }}-claim"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      bucket: shared
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
