apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{- with (lookup "v1" "Secret" "default" "k8s1regcred") }}
      {{- if index .data ".dockerconfigjson" }}
        {{ index .data ".dockerconfigjson" }}
      {{- end}}
    {{- end}}
